#!/bin/sh

if [ -f build.sbt ]
then
    echo The file, build.sbt, already exists.
    exit
fi

if [ -f pom.xml ]
then
    echo Creating SBT stuff
    scala -savecompiled "$0" "$@"
    mkdir -p project/build
    # cp /work/github/sbt-stuff/ProjectTools.scala project/build/
else
    echo The file, pom.xml, does not exist.
    exit
fi

exec sbt exit
!#

val defaultOrganization = "Beeherd"
val sbtVersion = "0.11"

val buildVersion = 
  if (args.size > 0) args(0)
  else "2.10.3"

println(buildVersion)

import java.io._

val pom = scala.xml.XML.loadFile(new File("pom.xml"))

val name = (pom \ "artifactId").text.trim
val organization = {
    val tmp = (pom \ "organization" \ "name").text.trim
    if (tmp.isEmpty) {
        println("Using default organization, " + defaultOrganization);
        defaultOrganization
    } else {
        tmp
    }
}
val version = (pom \ "version").text.trim

val projectDir = new File("project")
projectDir.mkdirs()

val buildProps = new File("build.sbt")

writeLines(buildProps
  , "name := \"" + name + "\"\n"
  , "version := \"" + version + "\"\n"
  , "scalaVersion := \"" + buildVersion + "\"\n"
  , "libraryDependencies += \"com.novocode\" % \"junit-interface\" % \"0.10-M2\" % \"test\"\n" 
)

def writeLines(target: File, lines: String*): Unit = 
  writeLines(target, lines.toList)

def writeLines(target: File, lines: List[String]): Unit =
    use(new FileWriter(target)) {w => lines.foreach {l => w.write (l + "\n") }}

def use[R <: Closeable, T](closeable: R)(f: (R) => T): T = {
  try {
      f(closeable)
  } finally {
      try { closeable.close() } catch { case e:Exception => {}}
  }
}
