#!/bin/sh

if [ ! -f pom.xml ]
then
    echo Did not find a pom.xml.  Exiting.
fi

if [ -d lib ]
then
    rm -f lib/*.jar
else
    mkdir lib
fi
 
mvn dependency:copy-dependencies
#mvn dependency:copy-dependencies -DincludeScope=runtime
#mvn dependency:copy-dependencies -DexcludeTransitive=true
cp target/dependency/* lib/
